### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by AdamCaviness** [nickela125/BuildNotifications#1]
This is an interesting project and I'd love to look further.  Could you please commit the missing BuildDefinition.cs, BuildStatus.cs and IBuildStatus.cs files?  Thanks.

**Comment by nickela125** [comment]
Hi, thanks for the interest. I have been pushing my commits to this project to a VSO repository (to test the notifications as I develop), so the code will look quite different now. I have put my latest code up here for you now. There are a few things I still want to finish / change, but the core functionality has been working fine for my use case at the moment. Enjoy!
